openapi: "3.0.0"
info:
  title: "eyevow api"
  description: ""
  version: "1.0.0"
servers:
  - url: https://eyevow.com/api

# ----
# エンドポイント
# ----

paths:

  # ログイン

  /api/login/:
    post:
      tags:
        - 認証
      summary: ログイン
      requestBody:
        content:
          application/json:
            schema:
              properties:
                provider:
                  type: string
                  enum: ["google", "line", "twitter"]
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  redirect_url:
                    type: string
  
  # 誓い

  /api/vows/:
    get:
      tags:
        - 誓い
      summary: みんなの誓いを確認する
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  vows:
                    type: array
                    items:
                      $ref: '#/components/schemas/Vow'
  /api/vows/{id}/cheers/:
    post:
      tags:
        - 応援
      summary: 応援する
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  vow:
                    $ref: '#/components/schemas/Vow'
  /api/vow:
    get:
      security:
        - AccessToken: []
      tags:
        - 誓い
      summary: 現在の誓いを確認する
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  vow:
                    $ref: '#/components/schemas/Vow'
    put:
      tags:
        - 誓い
      summary: 誓いを立てる
      requestBody:
        content:
          application/json:
            schema:
              properties:
                text:
                  type: string
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  vow:
                    $ref: '#/components/schemas/Vow'
  /api/archived/:
    get:
      tags:
        - 達成
      summary: 達成済みの誓いを確認する
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  vows:
                    type: array
                    items:
                      $ref: '#/components/schemas/Vow'
    post:
      tags:
        - 達成
      summary: 達成を報告する
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                properties:
                  vow:
                    $ref: '#/components/schemas/Vow'

# ----
# コンポーネント
# ----

components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      properties:
        id:
          type: string
    Vow:
      properties:
        id:
          type: string
        user:
          $ref: '#/components/schemas/User'
        text:
          type: string
        cheer_count:
          type: integer
        archived:
          type: boolean